### ISSUE TITLE
Comment locking in `process_detail` doesn't have correct permissions

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#119]
Comment threads can **only** be resolved by the original reporter. I can currently resolve and unlock all comment threads, at least in my testing.

**Comment by lilliputten** [comment]
Fixed in PR #120.

The feature is controlled (for now) by two `ThreadComments` configuration parameters (passing in the `setParams` method):

- `disableResolveByNonReporters` (`boolean`): Resolve/open function allowed only for thread reporter.
- `hideDisabledTitleActions` (`boolean`): Don't display disabled thread title actions.

(see `bw_matchbox/assets/modules/@types/ThreadComments.d.ts`, `TThreadCommentsParams` type).

Refactored thread rendering (extracted method for render only title actions, `ThreadCommentsRender:renderThreadTitleActions`).

So, it's possible to just disable or to completely hide disabled action buttons (depending on the `hideDisabledTitleActions` configuration parameter).

Just disabled:
![0826-215357](https://github.com/cauldron/bw_matchbox/assets/6855837/fda4aea9-1ad6-46fe-a725-7d7c63f81031)

Completely hidden:
![0826-221135](https://github.com/cauldron/bw_matchbox/assets/6855837/96425a29-6edd-42f8-a7ae-8689593dc935)
