### ISSUE TITLE
Allocation webpage: Visual indication when dragging into a group

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#134]
When dragging into a group, the group field should highlight or otherwise give some indication that you are in the right target.

**Comment by lilliputten** [comment]
Fixed in cff9bf2 @dev-230901-issue-128-allocation-page: Issue #134: Finished visual indication for drag-n-drop feature: Moved drag-n-drop functional to dediacted module (`AllocatePageInputsDragger.js`), added indication for added/moved items (`CommonIndicators.js`), minor fixes (added check for already loaded dynamic css (`CommonHelpers:addCssStyle`).
