### ISSUE TITLE
Revise main index view

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#41]
Main index view needs to be better. 

<img width="1672" alt="Screenshot 2023-08-05 at 16 04 10" src="https://github.com/cauldron/bw_matchbox/assets/645217/c9b08cf7-62bd-4590-ad41-979028056475">

We need additional filters in the same row as the existing order by filters, for:

Database:

* Source
* Target
* Proxy

This should be used to construct the API call, e.g. `GET /processes?database={value here}&order_by=random&offset=0&limit=25`

Filter:

* Matched (API call GET parameter: `filter=matched`)
* Unmatched (API call GET parameter: [`filter=unmatched`](https://github.com/cauldron/bw_matchbox/blob/327e8ac07fd5461a510f7ff8b515855ea5b0a690/bw_matchbox/webapp.py#L302))
* Waitlisted (API call GET parameter: `filter=waitlist`)

**Comment by lilliputten** [comment]
Fixed in PR #44:

- Issue #41: Update filter API for processes list pages: Added radio group for the `filter` parameter, added displaying of remain records inside the `Load more` button (eg: 'Load more(next NN out of NNN available)') (see `updateAvailableRecordsInfo` method of the `ProcessesListStates.js` module), added dynamic update of order and filter radio groups states based on default values (see `defaultOrderBy` and `defaultFilterBy` parameters in the `ProcessesListConstants.js` and `start` method of the `ProcessesListStates.js` modules), updated `/processes` request construction.

- Issue #1: Refactor: Write safe config file (`config.toml`) with unix-style line endings ('\n') and regular (unix-style) slashes in the `output_dir` file name (even on windows).

![0805-232211](https://github.com/cauldron/bw_matchbox/assets/6855837/446cb7da-4edc-41ad-b78b-c3afa39791ac)
![0805-232152](https://github.com/cauldron/bw_matchbox/assets/6855837/7ccce998-4ca0-4248-b338-2b4d5db79742)
![0805-233516](https://github.com/cauldron/bw_matchbox/assets/6855837/9206d97e-b6da-4443-8d97-9cce0f79adcb)

**Comment by cmutel** [comment]
@lilliputten Reopening this as we have one more radio button set, namely the database. I tried to add this myself but am not sure about scoping and how to populate the text strings from the HTML templates. Basically, the last set of radio buttons should offer the choice of database to search inside, namely:

* Source
* Target
* Proxy

The label can be simply "Database" (with the choice of Source, Target, Proxy - the user can see these labels for these three in the header).

I added the labels for these three in 553f7be785a668a11efc86d45d28935b18f8b904, but probably this is not the right place for access by the `ProcessList` functions.

**Comment by lilliputten** [comment]
Is it another parameter, not the same that we using now, from the server one (`database: '{{ database }}'`, resolving, for example into smth like 'USEEIO-1.1')?

How should we resolve this conflict between server and the client data?

Probably, if the client has not made a choice yet, we should use the server value. But if the client has made some choice, then we should use this value already?

Should we add the 'default' option (aka 'use server data') so that the user can cancel his previous choice?

> * Source

**Comment by cmutel** [comment]
> Is it another parameter, not the same that we using now, from the server one (database: '{{ database }}', resolving, for example into smth like 'USEEIO-1.1')?

It is the same parameter, but currently we don't give the users the option to change it. I want to be able to browse the other two databases in addition to the "Source" database.

The default is the same as what we use right now, the "Source" database.

**Comment by lilliputten** [comment]
Fixed in #47.
