### ISSUE TITLE
Fix design for buttons which do bad things

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#82]
cf45f367202a2e3bcaa99dcf86feef3863e30478 added a `button-danger`, but the style could be improved. @lilliputten please make this look a bit nicer.

**Comment by lilliputten** [comment]
Fixed in PR #97.

See buttons and icons samples in demo:

![0810-181546](https://github.com/cauldron/bw_matchbox/assets/6855837/26914d14-e47a-4d4e-9d9a-7a6a26235cde)

In real pages (actual state):

![0810-182221](https://github.com/cauldron/bw_matchbox/assets/6855837/51bbbe54-9d60-424b-a2ca-5e5b41451afc)
![0810-181753](https://github.com/cauldron/bw_matchbox/assets/6855837/2eab7eb7-d4eb-4874-ad12-bbf36531ede3)
