### ISSUE TITLE
Add order by `importance` to `index` view

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#85]
08201380805826a857f1d17383ae712852704643 added the ability to order processes by "importance", calculated using the page rank algorithm. It would be good to add this to the list of "Order by" possibilities in the index page. Please note that ordering by importance is *only available on the `source` database*, and this restriction should be handled in javascript.

**Comment by lilliputten** [comment]
Fixed in PR #98.

![0810-210133](https://github.com/cauldron/bw_matchbox/assets/6855837/215f9cbd-5cf3-407b-8ebb-8cce59cc6985)
![0810-210143](https://github.com/cauldron/bw_matchbox/assets/6855837/b16ad486-269e-4854-8624-2e7b30e283e4)
![0810-210158](https://github.com/cauldron/bw_matchbox/assets/6855837/f18fa90a-452d-4fed-997e-fe4df7b818ee)
